### ISSUE TITLE
Idea: allow a base modeltree whose attributes others would inherit

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/modeltree#16]
E.g.:

    MODELTREES = {
        '_BASE': {
            'excluded_models': [...],
            'required_routes': [...],
            'excluded_routes': [...],
        }
        'default': {'model': 'core.Person'},
        'genes.gene': {'model': 'genes.Gene'},
        'genes.transcript': {'model': genes.Transcript'},
    }

If the _BASE settings were applied to any modeltree created, even outside the configuration phase, then those last two modeltree definitions could be left off.

My motivation is a Harvest app with a complex model tree and a custom query processor that applies a custom condition to queries.  The query processor uses the M() function to generate a Django query filter string for the condition, based on the base model for the query.  The Harvest field stats and values queries are not based on the default model, so the same custom routing attributes have to be applied to many different modeltrees.  I can do this in a pseudo-DRY way like this:

    BASE_MT = {
        'excluded_models': [...],
        'required_routes': [...],
        'excluded_routes': [...],
    }
    MODELTREES = {
        'default': dict(BASE_MT, model='core.Person'),
        'genes.gene': dict(BASE_MT, model='genes.Gene'),
        'genes.transcript': dict(BASE_MT, model='genes.Transcript'),
        ...
    }

but a simple inheritance scheme would probably be better.

**Comment by bruth** [comment]
This is quite an old issue, but I suppose this could be easily solved by deep-copying a *base* dict and setting the changed fields where needed?

**Comment by murphyke** [comment]
I can just barely remember this.  Looking at it now, the workaround seems pretty good, though, maybe even preferable.  If you want to close the issue and move on, that seems reasonable.
