### ISSUE TITLE
2.0.1 Release 

### ISSUE THREAD

**Issue by naegelyd** [chop-dbhi/modeltree#29]
With the Python and Django compatibility fixes in https://github.com/chop-dbhi/modeltree/pull/28 and https://github.com/chop-dbhi/modeltree/pull/27, it would be good to publish a 2.0.1 final release. @bruth when you have time, can you release the 2.0.1 final to PyPi? I don't _think_ I can do that but if I can let me know and I'd be happy to do it.

**Comment by bruth** [comment]
@naegelyd It appears other maintainers can be added to packages on PyPi. What is your username? I will add you to the Harvest related packages.
